### ISSUE TITLE
Document process of setting up project in Terraform (how to setup a dev environment)

### ISSUE THREAD

**Issue by michellecampo** [broadinstitute/infra20#14]
The google drive document is https://docs.google.com/spreadsheets/d/1DY8YUFy4w4PFK3JxQGWf4q28bGVCXVqzJuQY-owtTdk/edit#gid=0

**Comment by spatilbroad** [comment]
PR https://github.com/broadinstitute/infra20/pull/31 for this is merged.  We can close this issue now.
